# Wrapper de compatibilidade para a Sprint 2.
# A implementação Java canônica está em ../../assinador.

ASSINADOR_DIR := ../../assinador

.PHONY: all test samples clean

all:
	$(MAKE) -C $(ASSINADOR_DIR) all

test:
	$(MAKE) -C $(ASSINADOR_DIR) test

samples:
	$(MAKE) -C $(ASSINADOR_DIR) samples

clean:
	$(MAKE) -C $(ASSINADOR_DIR) clean
